### ISSUE TITLE
内存泄露问题很严重

### ISSUE THREAD

**Issue by LeeWongSnail** [zhaoxiaobao/inke-ios#3]
拉流界面的控制器没有被释放，存在较大的内存泄露问题！ 既然开源了 也要注意质量哈！
收到内存警告的时候 在方法中 执行了 [_decoder openFile:nil error:nil];  这个在内部已经做了断言 传nil是肯定会报错的！直接导致了崩溃
![default](https://cloud.githubusercontent.com/assets/10498869/16291532/83aaedf6-393a-11e6-8a59-dacd4093855e.png)

**Comment by zhaoxiaobao** [comment]
呜呜、非常感谢有问题能提出来。没太多时间好好搞，有空我再慢慢完善。<^ $ ^>

**Comment by LeeWongSnail** [comment]
恩 能做到这里已经很不错了  我们最近也在玩直播 有时间 帮你打理一下

**Comment by lawwilte** [comment]
我最近也在搞直播，大家能不能一起建个群，一起研究这方面的知识
